# Generated by Django 4.2.2 on 2023-07-25 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=300)),
                (
                    "emaillist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.emaillist"
                    ),
                ),
            ],
        ),
    ]
